WS: fix build error from incomplete delay -> delay_us rename
Commit 41b710a renamed 'delay' to 'delay_us' but missed two uses in
the snapshot scheduling block, breaking compilation:

  src/WS.cpp:2017:39: error: 'delay' was not declared in this scope

Signed-off-by: Paul Philippov <paul@themactep.com>